baseURL = 'http://blog.karsa.info/'
languageCode = 'en-us'
title = "Karsa Wang 's Blog"
theme = 'smigle'
appendPort = false

[params]
  author = 'Karsa Wang'
  description = "记录一些问题，也许对其他人也有所助益"
  subtitle = "记录一些问题，也许对其他人也有所助益"

[taxonomies]
  tag = "tags"
  series = "series"
  category = "categories"

[markup.goldmark.renderer]
    unsafe = true

[[menu.main]]
  identifier = "home"
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  identifier = "post"
  name = "Posts"
  url = "/posts"
  weight = 2

[[menu.main]]
  identifier = "tags"
  name = "Tags"
  url = "/tags"
  weight = 3
